---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    author: Vamsi
spec:
  type: LoadBalance
  ports:
    - targerport: 80
      port: 80
  selector:
    author: Vamsi
    name: voting-app
...
